data:
  raw_path: data/raw  
  processed_path: data/processed

features:
  rename: 
    calculation time: timestamp
    speed(km/h): speed
    mean travel time (mins): mean_travel_time
    actual delay (mins): delay
  encode: 
    one_hot: trend
  drop:
    - speed(mph)
    - current delay (mins)
  target: delay
  
